EXIT_CODE_FINAL_STATUS_SUCCESS = 0
EXIT_CODE_UNKNOWN_ERROR = 3

EXIT_CODE_FILE_WRITE_ERROR = 100

EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_INVALID_PROJECT = 201
EXIT_CODE_INVALID_WORKBOOK = 202
EXIT_CODE_INVALID_VIEW = 203
EXIT_CODE_INVALID_JOB = 204
EXIT_CODE_INVALID_DATASOURCE = 205
EXIT_CODE_REFRESH_ERROR = 205

EXIT_CODE_FINAL_STATUS_CANCELLED = 210
EXIT_CODE_FINAL_STATUS_ERRORED = 211
EXIT_CODE_STATUS_INCOMPLETE = 212
